spring:
 profiles:
  active:
  - dev
---
spring:
 profiles: dev #开发环境
 application: miscroservicecloud-config-ms-dev
---
spring:
 profiles: test #测试环境
 application:
  name:miscroservicecloud-config-ms-test
#保存为UTF-8格式