spring:
 profiles:
  active:
  - dev
  
---
server:
 port:8201
spring:
 profiles:dev
 application:
  name:miscroservicecloud-config-client
eureka:
 client:
 server-url:
  defaultZone:http://eureka-dev.com:7001/eureka/
  
---

server:
 port:8202
spring:
 application:
  name:miscroservicecloud-config-client
eureka:
 client:
 server-url:
  defaultZone:http://eureka-test.com:7001/eureka/